In [ ]:
#Importing the library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [ ]:
dataset = pd.read_csv('Dataset.csv')

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cd /content/drive/"My Drive/Colab Notebooks"

/content/drive/My Drive/Colab Notebooks


In [ ]:
print(dataset)

     FTHG  FTAG  HTHG  HTAG  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  \
0       3     0     2     0  23  12   11    2  15  15  16   7   1   2   0   0   
1       1     0     1     0   7  17    2   12  19  14   1   3   2   1   0   0   
2       0     0     0     0  13  12    9    7  12  13   4   8   1   3   0   0   
3       6     0     2     0  18  10   13    4  10  10   3   1   1   0   0   0   
4       2     2     1     0   6  13    2    7  13  10   3   6   3   3   1   0   
..    ...   ...   ...   ...  ..  ..  ...  ...  ..  ..  ..  ..  ..  ..  ..  ..   
375     3     3     2     0  15  13   10    7   5   8   7   6   0   0   0   0   
376     0     1     0     0  11  11    5    9  10   9   5   3   1   4   0   0   
377     2     1     0     0  22   7   16    3   5  15   7   5   0   3   0   0   
378     0     3     0     1  17  17   12   12   7   8   4   6   0   2   0   0   
379     2     3     0     3  12  13    5   10  12   9   8   3   3   1   0   0   

    FTR  
0     H  
1     H

In [ ]:
dataset.describe()

FTHG        FTAG        HTHG        HTAG          HS          AS  \
count  380.000000  380.000000  380.000000  380.000000  380.000000  380.000000   
mean     1.623684    1.173684    0.726316    0.526316   13.802632   11.063158   
std      1.240464    1.114236    0.817901    0.749207    4.772447    4.215340   
min      0.000000    0.000000    0.000000    0.000000    1.000000    2.000000   
25%      1.000000    0.000000    0.000000    0.000000   11.000000    8.000000   
50%      1.000000    1.000000    1.000000    0.000000   13.500000   11.000000   
75%      2.000000    2.000000    1.000000    1.000000   17.000000   13.000000   
max      7.000000    6.000000    4.000000    4.000000   32.000000   25.000000   

              HST         AST          HF          AF          HC          AC  \
count  380.000000  380.000000  380.000000  380.000000  380.000000  380.000000   
mean     7.657895    5.955263   10.986842   11.428947    6.044737    4.997368   
std      3.428703    2.956251    3.450721    3.481228    3.107672    2.834483   
min      0.000000    0.000000    3.000000    2.000000    0.000000    0.000000   
25%      5.000000    4.000000    8.000000    9.000000    4.000000    3.000000   
50%      7.000000    6.000000   11.000000   11.000000    5.000000    5.000000   
75%     10.000000    8.000000   13.000000   14.000000    8.000000    7.000000   
max     18.000000   20.000000   21.000000   24.000000   17.000000   16.000000   

               HY          AY          HR          AR  
count  380.000000  380.000000  380.000000  380.000000  
mean     1.413158    1.839474    0.076316    0.089474  
std      1.160173    1.304759    0.265853    0.303706  
min      0.000000    0.000000    0.000000    0.000000  
25%      1.000000    1.000000    0.000000    0.000000  
50%      1.000000    2.000000    0.000000    0.000000  
75%      2.000000    3.000000    0.000000    0.000000  
max      7.000000    7.000000    1.000000    2.000000

In [ ]:
dataset.head()

FTHG  FTAG  HTHG  HTAG  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  \
0     3     0     2     0  23  12   11    2  15  15  16   7   1   2   0   0   
1     1     0     1     0   7  17    2   12  19  14   1   3   2   1   0   0   
2     0     0     0     0  13  12    9    7  12  13   4   8   1   3   0   0   
3     6     0     2     0  18  10   13    4  10  10   3   1   1   0   0   0   
4     2     2     1     0   6  13    2    7  13  10   3   6   3   3   1   0   

  FTR  
0   H  
1   H  
2   D  
3   H  
4   D

In [ ]:
dataset.tail()

FTHG  FTAG  HTHG  HTAG  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  \
375     3     3     2     0  15  13   10    7   5   8   7   6   0   0   0   0   
376     0     1     0     0  11  11    5    9  10   9   5   3   1   4   0   0   
377     2     1     0     0  22   7   16    3   5  15   7   5   0   3   0   0   
378     0     3     0     1  17  17   12   12   7   8   4   6   0   2   0   0   
379     2     3     0     3  12  13    5   10  12   9   8   3   3   1   0   0   

    FTR  
375   D  
376   A  
377   H  
378   A  
379   A

In [ ]:
dataset.shape

(380, 17)

In [ ]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:,16].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           A       0.71      0.53      0.61        19
           D       0.38      0.38      0.38        24
           H       0.66      0.76      0.70        33

    accuracy                           0.58        76
   macro avg       0.58      0.55      0.56        76
weighted avg       0.58      0.58      0.58        76

[[10  8  1]
 [ 3  9 12]
 [ 1  7 25]]
